backend:
  name: github
  repo: pavelzajicek75-ops/zajda_web
  branch: main
  base_url: https://fancy-math-7491.pavel-zajicek75.workers.dev
  auth_endpoint: auth

media_library:
  name: uploadcare
  config:
    publicKey: 'demopublickey'

publish_mode: simple
show_preview_links: true

collections:
  - name: "clanky"
    label: "Moje Příspěvky"
    folder: "_posts"
    create: true
    delete: true # Tlačítko pro mazání v detailu příspěvku
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Jazyk", name: "lang", widget: "select", options: ["cs", "en"]}
      - {label: "Sekce", name: "section", widget: "select", options: ["Cestování", "Fotografování", "Mé projekty"]}
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Obrázek", name: "image", widget: "image"}
      - {label: "Text", name: "body", widget: "markdown"}
