backend:
  name: github
  repo: pavelzajicek75-ops/zajda_web
  branch: main
  base_url: https://fancy-math-7491.pavel-zajicek75.workers.dev
  auth_endpoint: auth

media_folder: "assets/img"
public_folder: "/assets/img"

media_library:
  name: uploadcare
  config:
    publicKey: 'demopublickey'
    # Zapínáme ruční editační nástroje
    effects: 'crop, rotate, enhance, sharp, blur'
    # Povolujeme manuální změnu rozlišení a kvality při nahrávání
    imageShrink: '1600x1600 80%' # Základní nastavení, které si v editoru doladíš
    tabs: 'file camera facebook instagram url'
    previewStep: true

locale: 'cs'

collections:
  - name: "obsah"
    label: "Veškerý obsah"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Hlavní sekce", name: "main_section", widget: "select", options: ["Fotografování", "Cestování", "Projekty"]}
      - {label: "Podsekce", name: "category", widget: "string"}
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Stát", name: "country", widget: "string", required: true}
      - {label: "Datum", name: "date", widget: "datetime", required: true}
      - {label: "Obrázek", name: "image", widget: "image"}
      - {label: "Text článku", name: "body", widget: "markdown"}
