backend:
  name: github
  repo: pavelzajicek75-ops/zajda_web
  branch: main

# PROPOJENÍ S CLOUDINARY - OPRAVENO
media_library:
  name: cloudinary
  config:
    cloud_name: dxf1lu1oi
    api_key: "593899341857225"
    default_transformations:
      - fetch_format: "auto"
        quality: "auto"

collections:
  - name: "posts"
    label: "Články / Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Sekce / Section", name: "section", widget: "select", options: ["Fotografování", "Cestování", "Projekty"]}
      - {label: "Titulek (CZ)", name: "title_cz", widget: "string"}
      - {label: "Title (EN)", name: "title_en", widget: "string"}
      - {label: "Úvodní fotka / Main Image", name: "image", widget: "image"}
      - {label: "Obsah (CZ)", name: "body_cz", widget: "markdown"}
      - {label: "Content (EN)", name: "body_en", widget: "markdown"}
      - {label: "Galerie / Gallery", name: "photos", widget: "list", field: {label: "Foto", name: "image", widget: "image"}}
